import * as Yup from "yup";

export const customerValidation = Yup.object().shape({
    // UID: Yup.string().required('UID is required'),
    // status: Yup.string().required('Status is required'),
    OwnerFName: Yup.string().required('Owner First Name is required'),
    // OwnerLName: Yup.string().required('Owner Last Name is required'),
    // OwnerCompanyName: Yup.string().required('Owner Company Name is required'),
    // RONumber: Yup.string().required('RO Number is required'),
    // CSRName: Yup.string().required('CSR Name is required'),
    // OwnerAddress1: Yup.string().required('Owner Address 1 is required'),
    // OwnerAddress2: Yup.string().required('Owner Address 2 is required'),
    // OwnerCity: Yup.string().required('Owner City is required'),
    // OwnerStateProvince: Yup.string().required('Owner State/Province is required'),
    // OwnerPostalZip: Yup.string().required('Owner Postal/Zip Code is required'),
    // OwnerEmail: Yup.string().email('Invalid email format').required('Owner Email is required'),
    // OwnerCellPhone: Yup.string().required('Owner Cell Phone is required'),
    // VehicleArrivedDate: Yup.date().required('Vehicle Arrived Date is required'),
    // RepairStartedDate: Yup.date().required('Repair Started Date is required'),
    // DeliveredDate: Yup.date().required('Delivered Date is required'),
    // VehicleYear: Yup.string().required('Vehicle Year is required'),
    // VehicleMake: Yup.string().required('Vehicle Make is required'),
    // VehicleModel: Yup.string().required('Vehicle Model is required'),
    // BusinessKeyPSG: Yup.string().required('Business Key PSG is required'),
    // BUName: Yup.string().required('BU Name is required'),
    // purl_id: Yup.string().required('PURL ID is required'),
    // OwnerWorkPhone: Yup.string().required('Owner Work Phone is required'),
    // OwnerHomePhone: Yup.string().required('Owner Home Phone is required'),
    // OwnerCountryCode: Yup.string().required('Owner Country Code is required'),
    // OwnerNightPhone: Yup.string().required('Owner Night Phone is required'),
    // OwnerDayPhone: Yup.string().required('Owner Day Phone is required'),
    // OwnerOtherPhone: Yup.string().required('Owner Other Phone is required'),
    // ReferralSourceName: Yup.string().required('Referral Source Name is required'),
    // InsuranceCompany: Yup.string().required('Insurance Company is required'),
    // ClaimType: Yup.string().required('Claim Type is required'),
    // TotalLaborHrs: Yup.number().required('Total Labor Hours are required'),
    // GrossAmount: Yup.number().required('Gross Amount is required'),
    // TotalLoss: Yup.number().required('Total Loss is required'),
    // InsuranceAgentName: Yup.string().required('Insurance Agent Name is required'),
    // EstimatorName: Yup.string().required('Estimator Name is required'),
});
