import * as Yup from "yup";
export const shopValidation = Yup.object({
  active: Yup.boolean().required("Required*"),
  advantage_active: Yup.boolean().required("Required*"),
  mso_shop: Yup.boolean().required("Required*"),
  part_of_mso: Yup.boolean().required("Required*"),
  mapping: Yup.boolean().required("Required*"),
  shop_name: Yup.string().required("Shop name is required"),

  m_shop_name_display:  Yup.string().required("Shop name display is required"),
  psg_id:  Yup.string().required("Psg id  is required"),
  m_webaddress: Yup.string().required("webaddress is required"),
  // email: null,
  // phone_number: null,
  address1: Yup.string().required("Address 1 is required"),
  m_shop_city: Yup.string().required("City  is required"),
  m_shop_state: Yup.string().required("State is required"),
  // address2: null,
  m_shop_zip: Yup.string().required("Zip code 1 is required"),
  // first_name: null,
  // last_name: null,
  m_shop_signature_text: Yup.string().required("Shop Signature is required"),
  // email_from: null,
  // embed_type: null || "Gravity Form",
  // form_id: null,
  // survey_id: null,
  // google_review_link: null,
  // email_header: null,
  // name_rate: null,
  // billing_type: null,
  // use_all: null,
});
