import jsPDF from "jspdf";

export const generatePDF = (productData) => {
    const doc = new jsPDF();

    let y = 10;  // Define the starting position for text

    // Add Customer Information
    doc.text(`Customer Name: ${productData?.OwnerFName} ${productData?.OwnerLName}`, 10, y += 10);
    doc.text(`Company Name: ${productData?.OwnerCompanyName}`, 10, y += 10);
    doc.text(`Address: ${productData?.OwnerAddress1}, ${productData?.OwnerAddress2 ? productData?.OwnerAddress2 + ', ' : ''}${productData?.OwnerCity}, ${productData?.OwnerStateProvince} ${productData?.OwnerPostalZip}`, 10, y += 10);
    doc.text(`Email: ${productData?.OwnerEmail}`, 10, y += 10);
    doc.text(`Cell Phone: ${productData?.OwnerCellPhone}`, 10, y += 10);
    doc.text(`Home Phone: ${productData?.OwnerHomePhone}`, 10, y += 10);
    doc.text(`Work Phone: ${productData?.OwnerWorkPhone}`, 10, y += 10);
    doc.text(`Night Phone: ${productData?.OwnerNightPhone}`, 10, y += 10);
    doc.text(`Day Phone: ${productData?.OwnerDayPhone}`, 10, y += 10);

    // Vehicle Information
    doc.text(`Vehicle Year: ${productData?.VehicleYear}`, 10, y += 10);
    doc.text(`Vehicle Make: ${productData?.VehicleMake}`, 10, y += 10);
    doc.text(`Vehicle Model: ${productData?.VehicleModel}`, 10, y += 10);
    doc.text(`Vehicle Arrived Date: ${productData?.VehicleArrivedDate}`, 10, y += 10);

    // Claim Information
    doc.text(`Claim Type: ${productData?.ClaimType}`, 10, y += 10);
    doc.text(`Insurance Company: ${productData?.InsuranceCompany}`, 10, y += 10);
    doc.text(`Estimator Name: ${productData?.EstimatorName}`, 10, y += 10);
    doc.text(`Insurance Agent: ${productData?.InsuranceAgentName}`, 10, y += 10);
    doc.text(`Gross Amount: $${productData?.GrossAmount}`, 10, y += 10);
    doc.text(`Total Loss: $${productData?.TotalLoss}`, 10, y += 10);

    // Repair Information
    doc.text(`Repair Started Date: ${productData?.RepairStartedDate}`, 10, y += 10);
    doc.text(`Delivered Date: ${productData?.DeliveredDate}`, 10, y += 10);
    doc.text(`Total Labor Hours: ${productData?.TotalLaborHrs}`, 10, y += 10);
    doc.text(`RONumber: ${productData?.RONumber}`, 10, y += 10);

    // Shop Information
    doc.text(`Shop Name: ${productData?.shop_name?.shop_name}`, 10, y += 10);
    doc.text(`Shop Address: ${productData?.shop_name?.address1}, ${productData?.shop_name?.m_shop_city}, ${productData?.shop_name?.m_shop_state} ${productData?.shop_name?.m_shop_zip}`, 10, y += 10);
    doc.text(`Shop Contact: ${productData?.shop_name?.phone_number}`, 10, y += 10);
    doc.text(`Shop Email: ${productData?.shop_name?.email}`, 10, y += 10);

    // Adding a footer or signature text
    doc.text("Report generated by: Alioto's Garage", 10, y += 10);
    doc.text("Signature: ________________________", 10, y += 10);

    // Output the PDF to a new tab
    const pdfOutput = doc.output('bloburl');
    window.open(pdfOutput, '_blank');
};
