import jsPDF from "jspdf";

export const generatePDF = (productData) => {
    const doc = new jsPDF();

    let y = 10;  // Define the starting position for text
    const pageHeight = doc.internal.pageSize.height; // Get page height

    // Helper function to add text and check for page overflow
    const addText = (text) => {
        // Check if we need to add a new page
        if (y + 10 > pageHeight) {
            doc.addPage();  // Add a new page
            y = 10;  // Reset y to start near the top of the new page
        }
        doc.text(text, 10, y);  // Add text at the current position
        y += 10;  // Increment y position for the next text line
    };

    // Add Customer Information
    addText(`Customer Name: ${productData?.OwnerFName} ${productData?.OwnerLName}`);
    addText(`Company Name: ${productData?.OwnerCompanyName}`);
    addText(`Address: ${productData?.OwnerAddress1}, ${productData?.OwnerAddress2 ? productData?.OwnerAddress2 + ', ' : ''}${productData?.OwnerCity}, ${productData?.OwnerStateProvince} ${productData?.OwnerPostalZip}`);
    addText(`Email: ${productData?.OwnerEmail}`);
    addText(`Cell Phone: ${productData?.OwnerCellPhone}`);
    addText(`Home Phone: ${productData?.OwnerHomePhone}`);
    addText(`Work Phone: ${productData?.OwnerWorkPhone}`);
    addText(`Night Phone: ${productData?.OwnerNightPhone}`);
    addText(`Day Phone: ${productData?.OwnerDayPhone}`);

    // Add Vehicle Information
    addText(`Vehicle Year: ${productData?.VehicleYear}`);
    addText(`Vehicle Make: ${productData?.VehicleMake}`);
    addText(`Vehicle Model: ${productData?.VehicleModel}`);
    addText(`Vehicle Arrived Date: ${productData?.VehicleArrivedDate}`);

    // Add Claim Information
    addText(`Claim Type: ${productData?.ClaimType}`);
    addText(`Insurance Company: ${productData?.InsuranceCompany}`);
    addText(`Estimator Name: ${productData?.EstimatorName}`);
    addText(`Insurance Agent: ${productData?.InsuranceAgentName}`);
    addText(`Gross Amount: $${productData?.GrossAmount}`);
    addText(`Total Loss: $${productData?.TotalLoss}`);

    // Add Repair Information
    addText(`Repair Started Date: ${productData?.RepairStartedDate}`);
    addText(`Delivered Date: ${productData?.DeliveredDate}`);
    addText(`Total Labor Hours: ${productData?.TotalLaborHrs}`);
    addText(`RONumber: ${productData?.RONumber}`);

    // Add Shop Information
    addText(`Shop Name: ${productData?.shop_name?.shop_name}`);
    addText(`Shop Address: ${productData?.shop_name?.address1}, ${productData?.shop_name?.m_shop_city}, ${productData?.shop_name?.m_shop_state} ${productData?.shop_name?.m_shop_zip}`);
    addText(`Shop Contact: ${productData?.shop_name?.phone_number}`);
    addText(`Shop Email: ${productData?.shop_name?.email}`);

    // Add Footer or Signature
    addText("Report generated by: Alioto's Garage");
    addText("Signature: ________________________");

    // Output the PDF to a new tab
    const pdfOutput = doc.output('bloburl');
    window.open(pdfOutput, '_blank');
};
